# Generated by Django 4.2.9 on 2024-01-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='reciepe_description',
            new_name='receipe_description',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='reciepe_image',
            new_name='receipe_image',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='reciepe_name',
            new_name='receipe_name',
        ),
    ]
