# Generated by Django 4.2.9 on 2024-02-28 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receipes', '0007_reportcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='date_of_report',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report')},
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='dtae_of_report',
        ),
    ]
