# Generated by Django 4.2.9 on 2024-03-03 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes', '0008_reportcard_date_of_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 3, 3, 5, 28, 58, 273881, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
