# Generated by Django 4.2.9 on 2024-03-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes', '0009_receipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
